# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 18:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='lat',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='lon',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
